name: Build and Deploy Docker Image

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Check for Dockerfile
        id: check_dockerfile
        run: |
          if [ ! -f ./Dockerfile ]; then
            echo "Dockerfile not found, skipping build."
            exit 0
          fi

      - name: Set up QEMU
        if: success()
        uses: docker/setup-qemu-action@v2

      - name: Login to DmytroRegistry
        if: success()
        uses: docker/login-action@v3
        with:
          registry: registry.dmytroframe.com
          username: ${{ secrets.DMYTROREGISTRY_USERNAME }}
          password: ${{ secrets.DMYTROREGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v3

      - name: Extract repository name
        id: extract_repo
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: registry.dmytroframe.com/${{ env.REPO_NAME }}:${{ github.ref_name }}
